### ISSUE TITLE
Informative error logging in case components can't be updated

### ISSUE THREAD

**Issue by immortaly007** [oxyno-zeta/prometheus-cachethq#6]
**Is your feature request related to a problem? Please describe.**
First of all, thanks for creating this code! It seems to be very versatile and exactly what I need! 
However, something is not going right for me, as the alerts don't arrive in cachet. I do see in the logs that the alertmanager notifications arrive (note that 172.29.0.8 is the IP for the alertmanager)

```
time="2020-11-08T23:32:46Z" level=debug msg="request started" client_ip=172.29.0.8 http_method=POST http_proto=HTTP/1.1 http_scheme=http remote_addr="172.29.0.8:58132" request_id=e3f6340c-4ef2-49e6-935c-c10e9e8b29cf uri="http://prometheus-cachet:8080/prometheus/webhook" user_agent=Alertmanager/0.20.0

time="2020-11-08T23:32:46Z" level=error msg="request complete" client_ip=172.29.0.8 http_method=POST http_proto=HTTP/1.1 http_scheme=http remote_addr="172.29.0.8:58132" request_id=e3f6340c-4ef2-49e6-935c-c10e9e8b29cf resp_bytes_length=31 resp_elapsed_ms=68.073926 resp_status=404 uri="http://prometheus-cachet:8080/prometheus/webhook" user_agent=Alertmanager/0.20.0
```
I don't know what is going wrong here. Is prometheus-cachethq not able to match the alert to a rule? Is it unable to connect to cachet? And in that case, is the problem the cachet URL or the API key? Or is it unable to match the component in the configuration to an existing component in cachet?

I think having more clear logging would greatly enhance the debugging experience. Unfortunately, I'm not a "Go" coder myself, so I'm unsure how I would go about debugging this, so I would be amazing if you could help!

**Describe the solution you'd like**
It would be nice if the logging would indicate in which part of the proces the error is originating, and, in more general terms, why my component in cachet isn't updating. 

**Describe alternatives you've considered**
I have tried to put the log level to "trace", but this didn't really reveal any additional information. 

**Additional context**
I'm running in docker. A snippet of the docker-compose file I use:

```yml
services:
  // Prometheus, node_exporter, cadvisor, alertmanager, etc here
  cachet:
    image: cachethq/docker:latest
    env_file:
      - ./cachet/config.env
    ports:
      - 8000
  prometheus-cachet:
    image: oxynozeta/prometheus-cachethq
    volumes:
      - ./cachet/prometheus-cachet:/conf
    ports:
      - 8080
      - 9090
```

And this is the config for prometheus-cachet I am using:
```yml
# Log configuration
log:
  # Log level
  level: trace
  # Log format
  format: text

# Server configurations
# server:
#   listenAddr: ""
#   port: 8080

# Cachet configuration
cachet:
  url: http://cachet:8000
  apiKey: <redacted>

# Targets
  - component:
      name: nginx-test
      group: WHEATLEY
      status: MAJOR_OUTAGE
    alerts:
      - name: blackbox_probe_failed
      - labels:
          instance: https://nginx-test.mydomain.com
```

And the labels for the (test) alert I'm triggering are:
```
alertname="blackbox_probe_failed"
instance="https://nginx-test.mydomain.com"
job="blackbox-http-2xx"
severity="page"
```

**Comment by oxyno-zeta** [comment]
Hello @immortaly007 ,

Thanks for your issue and happy to see that this code can help people :).

I must confess that I forgot to log the error before ending the request... That's pretty annoying, you are right.
I will make another version later today.

By the way, your configuration of prometheus-cachet seems weird to me. There isn't any `targets` key in your pasted one. Is it bad copy/paste or a real problem ?

Should be:
```yaml
# Log configuration
log:
  # Log level
  level: trace
  # Log format
  format: text

# Server configurations
# server:
#   listenAddr: ""
#   port: 8080

# Cachet configuration
cachet:
  url: http://cachet:8000
  apiKey: <redacted>

# Targets
targets:
  - component:
      name: nginx-test
      group: WHEATLEY
      status: MAJOR_OUTAGE
    alerts:
      - name: blackbox_probe_failed
      - labels:
          instance: https://nginx-test.mydomain.com
```

**Comment by immortaly007** [comment]
Thank you for responding so quickly!

Regarding the missing `targets:`, great eye for spotting that! In my real configuration there was actually another "target", but I guess when I took that one out of the configuration here, I deleted too much (it was a bit late last night when I opened this issue)

For your last comment, regarding the "`blackbox_probe_failed` OR contains labels", that is a mistake in my real configuration. To get it to trigger when "alert name is `blackbox_probe_failed` AND contains labels...", I should probably just remove the hyphen in front of the `labels` tag, like so, right?
```yml
# Targets
targets:
  - component:
      name: nginx-test
      group: WHEATLEY
      status: MAJOR_OUTAGE
    alerts:
      - name: blackbox_probe_failed
        labels:
          instance: https://nginx-test.example.com
```

Once again, thank you for responding so quickly, and I'm looking forward to the updated version!
