### ISSUE TITLE
Informative error logging in case components can't be updated No.2

### ISSUE THREAD

**Issue by thomas315** [oxyno-zeta/prometheus-cachethq#7]
**Is your feature request related to a problem? Please describe.**
I'm just evaluating this component as an alternative to a middleware component I'm already using.
Unfortunately I'm struggling with the initial setup. I can't get my components updated and always getting following error message:
```
prometheus-cachethq_oxy_1  | time="2021-06-15T09:50:43Z" level=debug msg="Configuration successfully loaded and logger configured"
prometheus-cachethq_oxy_1  | time="2021-06-15T09:50:43Z" level=info msg="Starting prometheus-cachethq version: 1.1.1 (git commit: e14df6b) built on 2020-11-09T17:27:14Z"
prometheus-cachethq_oxy_1  | time="2021-06-15T09:50:43Z" level=info msg="Server listening on :8080"
prometheus-cachethq_oxy_1  | time="2021-06-15T09:50:43Z" level=info msg="Server listening on :9090"
prometheus-cachethq_oxy_1  | time="2021-06-15T09:51:16Z" level=debug msg="request started" client_ip=172.26.0.1 http_method=POST http_proto=HTTP/1.1 http_scheme=http remote_addr="172.26.0.1:59186" request_id=5172ad0d-4e40-4c66-a2c6-ed25fc1a7e8b uri="http://localhost:8080/prometheus/wehbook" user_agent=curl/7.58.0
prometheus-cachethq_oxy_1  | time="2021-06-15T09:51:16Z" level=error msg="request complete" client_ip=172.26.0.1 http_method=POST http_proto=HTTP/1.1 http_scheme=http remote_addr="172.26.0.1:59186" request_id=5172ad0d-4e40-4c66-a2c6-ed25fc1a7e8b resp_bytes_length=-1 resp_elapsed_ms=0.048 resp_status=404 uri="http://localhost:8080/prometheus/wehbook" user_agent=curl/7.58.0
```
I already read through this reported [issue](https://github.com/oxyno-zeta/prometheus-cachethq/issues/6).

**Describe the solution you'd like**
Some suggestions what else I could try to get it running
or
More output when debug logs are on, e.g. seeing how a request is sent out with what parameters and why it fails instead of a non-informative 404 error.

**Describe alternatives you've considered**
- I tried several different configuration variations with or without `groupName` or `labels` e.g.
- simple curl command against http://localhost:8080/prometheus/wehbook is giving 404 as well
- Cachet API key should be correct because it's working for the other middleware in the same setup

**Additional context**
My setup:
docker-compose
```
  prometheus-cachethq_oxy:
    ports:
      - "8080:8080"
      - "9099:9090"
    image: oxynozeta/prometheus-cachethq:1.1.1
    volumes:
      - ./oxy_config.yml/:/conf/config.yaml
```
prometheus-cachethq configuration:
```
# Log configuration
log:
  # Log level
  level: debug
  # Log format
  format: text

# Server configurations
#server:
#  listenAddr: "0.0.0.0"
#  port: 8080

# Cachet configuration
cachet:
  url: http://cachet:8000
  apiKey: <redacted>

# Targets
targets:
  - component:
      name: testcomponent
#      groupName: test
      status: MAJOR_OUTAGE
    alerts:
      - name: testcomponent
```
crafted alertmanager request:
```
curl -X POST http://localhost:8080/prometheus/wehbook -d '{"receiver":"cachethq-receiver","status":"firing","alerts":[{"status":"firing","labels":{"alertname":"testcomponent"},"annotations":{},"startsAt":"2018-05-22T20:00:32.729840058-04:00","endsAt":"0001-01-01T00:00:00Z","generatorURL":""}],"groupLabels":{"alertname":"testcomponent"},"commonLabels":{"alertname":"testcomponent"},"commonAnnotations":{},"externalURL":"http://localhost.localdomain:9093","version":"4","groupKey":"{}:{alertname=\"testcomponent\"}"}'
```

Would be great if you can give me some hints what I might do wrong here. Thank you very much!
